services: 
  redis:
    image: redis
    ports:
      - '6379:6379'
  server: 
    build:
     context: server
    ports: 
      - '5000:5000'
  client:
    build:
      context: client
    ports:
      - '3000:3000'
    depends_on:
      - server